### ISSUE TITLE
Allow adding additional airlines

### ISSUE THREAD

**Issue by perdian** [perdian/flighttracker#6]
Not all airlines from the Openflights data represent the latest state or have the complete information for every case. For example the IATA code for Hamburg Airways is "HK" (https://en.wikipedia.org/wiki/Hamburg_Airways) which is not listed in the Openflights data (https://github.com/jpatokal/openflights/blob/master/data/airlines.dat).

Instead the "HK" IATA code is used for two other airlines: Four Star Aviation and Yangon Airways.

It should be possible to have both a way of adding a new airline into the list of airlines used by the Flighttracker application as well as specifying which Airline should be used when looking up an IATA airline code.

An implementation idea would be to have an additional database table that can be populated with airline information and which is used from within the AirlinesRepositoryImpl to populate the internal Map from String to AirlineEntity *after* the initial data has been loaded from the Openflights resource file.

**Comment by EmQsed** [comment]
Hi sorry to reopen this issue but I'm having the same issue. I have conflicting IATA codes for Vueling VY and can't seem to find a way to fix it.
